In [13]:
#import dependencies
import pandas as pd
import numpy as np

#importing models
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier

#preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

#metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [7]:
#importing data
file_path = "BERT_Vectorized_100features_Output.xlsx"

data = pd.read_excel(file_path)
X = data.iloc[:,2:]
y = data["Label"].replace("Non-Fact",0).replace("Fact",1)
data

C:\Users\lokan\AppData\Local\Temp\ipykernel_38232\1417671583.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y = data["Label"].replace("Non-Fact",0).replace("Fact",1)

,Doc,Label,BERT_0,BERT_1,BERT_2,BERT_3,BERT_4,BERT_5,BERT_6,BERT_7,...,BERT_758,BERT_759,BERT_760,BERT_761,BERT_762,BERT_763,BERT_764,BERT_765,BERT_766,BERT_767
0,There are plenty of hosting providers to choos...,Non-Fact,0.314039,0.096763,-0.166665,0.145882,-0.359345,-0.038474,0.313304,0.601608,...,-0.282451,-0.415035,0.114867,-0.431336,-0.051990,-0.011453,-0.064496,-0.618579,0.459900,0.736118
1,"We always want services which are the fastest,...",Non-Fact,0.393192,0.171032,0.209558,-0.194656,-0.379902,-0.406852,0.594905,0.938382,...,-0.180226,-0.402688,-0.082817,-0.154606,0.096291,-0.013540,-0.065011,-0.361344,0.463318,0.569388
2,Shortly - we want the best and the most reason...,Non-Fact,-0.073521,0.068837,0.253889,-0.099670,-0.566145,-0.686888,0.116164,0.429550,...,-0.177832,-0.272035,0.021245,0.241438,-0.293393,-0.122826,-0.223002,-0.580682,0.037066,0.648089
3,It is obvious that people want to get the best...,Non-Fact,0.387407,0.212284,-0.150840,0.078315,-0.464038,-0.346590,0.245214,0.749683,...,-0.415321,-0.506572,0.048944,0.030651,-0.171638,0.190513,0.230232,-0.462040,0.311543,0.648566
4,You should also keep in mind that bigger price...,Non-Fact,0.134430,0.008681,-0.174537,-0.205683,-0.467311,-0.189289,0.313656,0.620594,...,-0.122535,-0.335588,0.260279,0.004990,-0.598765,0.276339,0.040999,-0.186682,0.215308,0.511361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,Only thing which is good for railways is their...,Non-Fact,0.161516,0.210470,-0.204178,0.214225,-0.318729,-0.583400,0.939928,1.368355,...,-0.156351,-0.004502,0.479235,-0.176509,-0.032642,0.431572,0.184357,-0.692268,0.734623,0.479824
338,As no Match for Indian Railway network.,Non-Fact,-0.921866,-0.164130,-0.056345,-0.448644,0.391894,-0.275587,0.226137,0.485121,...,0.299854,0.153040,0.453433,-0.089885,0.417342,-0.393329,-0.354841,-0.093357,0.545881,0.281811
339,It's too big and still expanding.,Non-Fact,0.202335,0.006101,0.246568,-0.284599,-0.111200,-0.252624,-0.009215,0.693450,...,-0.118128,-0.057134,0.097043,-0.057799,0.115356,-0.164278,-0.175091,-0.011470,0.268007,0.475782
340,But we need to improve there services also.,Non-Fact,0.120719,0.145969,-0.060910,-0.249467,-0.471112,-0.304388,0.564667,0.438675,...,-0.377391,-0.269670,0.013208,-0.178848,-0.171864,-0.117169,-0.070229,-0.292479,0.342494,0.247105
341,Thank you please upvote if you also like India...,Non-Fact,-0.044859,-0.116518,0.014706,-0.179872,-0.404592,-0.754047,0.495399,0.658666,...,0.261590,-0.253673,0.255669,-0.132856,-0.042803,0.223292,-0.258838,-0.582698,0.594416,0.382066

In [8]:
#Data preprocessing
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=42)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [14]:
def evaluate_model(model, X_train, X_test, y_train, y_test):

    model.fit(X_train, y_train)

    # Predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Metrics
    results = {
        "Train Accuracy": accuracy_score(y_train, y_train_pred),
        "Test Accuracy": accuracy_score(y_test, y_test_pred),

        "Train Precision": precision_score(y_train, y_train_pred, average='weighted', zero_division=0),
        "Test Precision": precision_score(y_test, y_test_pred, average='weighted', zero_division=0),

        "Train Recall": recall_score(y_train, y_train_pred, average='weighted', zero_division=0),
        "Test Recall": recall_score(y_test, y_test_pred, average='weighted', zero_division=0),

        "Train F1": f1_score(y_train, y_train_pred, average='weighted', zero_division=0),
        "Test F1": f1_score(y_test, y_test_pred, average='weighted', zero_division=0)
    }

    return results

In [15]:
#implementing models

svm = SVC(kernel='rbf', probability=True)
dt = DecisionTreeClassifier()
rf = RandomForestClassifier(n_estimators=100)
adaboost = AdaBoostClassifier(n_estimators=100)
nb = GaussianNB()
mlp = MLPClassifier(hidden_layer_sizes=(100,), max_iter=500)
xgboost = XGBClassifier(use_label_encoder=False,eval_metric='logloss')
catboost = CatBoostClassifier(verbose=0)

In [19]:

# ==========================================
# MODEL NAMES
# ==========================================
model_names = [
    "SVM", "Decision Tree", "Random Forest",
    "AdaBoost", "Naive Bayes", "MLP",
    "XGBoost", "CatBoost"
]

# ==========================================
# EVALUATE MODELS
# ==========================================
results = []

# SVM
res = evaluate_model(svm, X_train_scaled, X_test_scaled, y_train, y_test)
res["Model"] = "SVM"
results.append(res)

# Decision Tree
res = evaluate_model(dt, X_train, X_test, y_train, y_test)
res["Model"] = "Decision Tree"
results.append(res)

# Random Forest
res = evaluate_model(rf, X_train, X_test, y_train, y_test)
res["Model"] = "Random Forest"
results.append(res)

# AdaBoost
res = evaluate_model(adaboost, X_train, X_test, y_train, y_test)
res["Model"] = "AdaBoost"
results.append(res)

# Naive Bayes
res = evaluate_model(nb, X_train, X_test, y_train, y_test)
res["Model"] = "Naive Bayes"
results.append(res)

# MLP
res = evaluate_model(mlp, X_train_scaled, X_test_scaled, y_train, y_test)
res["Model"] = "MLP"
results.append(res)

# XGBoost
res = evaluate_model(xgboost, X_train, X_test, y_train, y_test)
res["Model"] = "XGBoost"
results.append(res)

# CatBoost
res = evaluate_model(catboost, X_train, X_test, y_train, y_test)
res["Model"] = "CatBoost"
results.append(res)

# ==========================================
# CREATE DATAFRAME
# ==========================================
results_df = pd.DataFrame(results)

results_df = results_df[
    ["Model",
     "Train Accuracy", "Test Accuracy",
     "Train Precision", "Test Precision",
     "Train Recall", "Test Recall",
     "Train F1", "Test F1"]
]
results_df

C:\Users\lokan\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:13:40] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

,Model,Train Accuracy,Test Accuracy,Train Precision,Test Precision,Train Recall,Test Recall,Train F1,Test F1
0,SVM,0.989011,0.840580,0.989206,0.839635,0.989011,0.840580,0.988982,0.838386
1,Decision Tree,1.000000,0.710145,1.000000,0.721442,1.000000,0.710145,1.000000,0.713427
2,Random Forest,1.000000,0.826087,1.000000,0.829015,1.000000,0.826087,1.000000,0.820416
3,AdaBoost,1.000000,0.811594,1.000000,0.818153,1.000000,0.811594,1.000000,0.813328
4,Naive Bayes,0.824176,0.724638,0.823287,0.739340,0.824176,0.724638,0.823548,0.728216
5,MLP,1.000000,0.826087,1.000000,0.829015,1.000000,0.826087,1.000000,0.820416
6,XGBoost,1.000000,0.826087,1.000000,0.825414,1.000000,0.826087,1.000000,0.822705
7,CatBoost,1.000000,0.811594,1.000000,0.809704,1.000000,0.811594,1.000000,0.809002